language: node_js
sudo: false
node_js:
- '0.12'
git:
  submodules: false
cache:
  directories:
  - node_modules
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && git submodule update --init --recursive && cd api-node && git fetch && git merge origin/production && cd .. || true'
install:
- npm install
- npm prune
before_script: npm test
script: npm run build
